version: '3.8'

services:
  vpn:
    image: dperson/openvpn-client
    container_name: risevpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ./risevpn.ovpn:/vpn/vpn.conf:ro
    environment:
      - OPENVPN_OPTS=--config /vpn/vpn.conf
    restart: unless-stopped

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imdb-scraper
    depends_on:
      - vpn
    environment:
      - IP_ROTATION=False
    volumes:
      - .:/app
    command: poetry run python main.py
    network_mode: "service:vpn"  # 🔥 Todo el tráfico va por la VPN
