services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper-tor
    env_file:
      - .env
    volumes:
      - .:/app
    command: poetry run python main.py  # este ya se sobrescribe en CMD, así que puedes quitarlo
